module.exports = ({ env }) => ({
<<<<<<< HEAD
    // ...
    plugins: {
      // ...
      'users-permissions': {
        jwtSecret: env('JWT_SECRET', 'jwtSecret')
      },
      // ...
    },
    // ...
  });
=======
  // ...
  plugins: {
    // ...
    'users-permissions': {
      jwtSecret: env('JWT_SECRET', 'jwtSecret')
    },
    // ...
  },
  // ...
});
>>>>>>> 399d366aca2b02f40225fe24cb8fbddcfc4af5f3
